version: '3'

services:
#  db:
#    container_name: mongod
#    image: "mongo:3.6"
#    env_file:
#     - .env
#    volumes:
#     - "${DB_PATH}:/data/db"

  api:
    container_name: api
    env_file:
     - .env
    build: .
#    environment:
#     - MONGODB_URI=mongodb://db:27017/parse-db
    ports:
     - "${PORT}:${PORT}"
#    links:
#     - db
#    depends_on:
#     - db

